version: "3"

networks:
  snippet-micro-bridge:
    driver: bridge

services:
  dev-consul:
    image: consul:1.9.11
    container_name: dev-consul
    hostname: dev-consul
    command: agent -server -client=0.0.0.0 -bootstrap -ui -node=consul1
    volumes:
      - ./.volumns/consul/kv:/consul/kv
    ports:
      - 8500:8500

  dev-rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: dev-rabbitmq
    hostname: dev-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.volumns/data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  dev-redis:
    image: redis:6.2.6
    container_name: dev-redis
    volumes:
      - ./.volumns/data/redis:/data
      - ./.volumns/data/redis/logs:/logs
    ports:
      - 6379:6379

  dev-mongo:
    image: mongo:5.0.7
    container_name: dev-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456    
    volumes:
      - ./.volumns/data/mongo:/data/db
      - ./.volumns/script/mongo/:/docker-entrypoint-initdb.d/

  dev-mysql:
    container_name: dev-mysql
    image: mysql:8.0.21
    privileged: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./.volumns/data/mysql:/var/lib/mysql