version: "3"

networks:
  snippet-micro-bridge:
    driver: bridge

services:
  dev-consul:
    image: consul:1.9.11
    container_name: dev-consul
    hostname: dev-consul
    volumes:
      - ./.volumns/consul/kv:/consul/kv
    ports:
      - 8500:8500

  dev-rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: dev-rabbitmq
    hostname: dev-rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./.volumns/data/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin

  dev-redis:
    image: redis
    container_name: dev-redis
    volumes:
      - ./.volumns/data/redis:/data
      - ./.volumns/data/redis/logs:/logs
    ports:
      - 6379:6379

  dev-mongo:
    image: mongo:latest
    container_name: dev-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456    
    volumes:
      - ./.volumns/data/mongo:/data/db

  dev-mysql:
    container_name: dev-mysql
    image: mysql:8.0.21
    privileged: true
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./.volumns/data/mysql:/var/lib/mysql

  dev-sw-es6:
    container_name: dev-sw-es6
    image: elasticsearch:6.8.15
    privileged: true
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    volumes:
      - ./.volumns/swes6/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  dev-sw-oap:
    container_name: dev-sw-oap
    image: apache/skywalking-oap-server:8.5.0-es6
    ports:
      - "1234:1234"
      - "11800:11800"
      - "12800:12800"
    depends_on:
      - dev-sw-es6
    links:
      - dev-sw-es6
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: dev-sw-es6:9200
      
  dev-sw-oap-ui:
    container_name: dev-sw-oap-ui
    image: apache/skywalking-ui
    privileged: true
    ports:
      - "9898:8080"
    depends_on:
      - dev-sw-es6
    links:
      - dev-sw-oap
    environment:
      SW_OAP_ADDRESS: dev-sw-oap:12800

  dev-elk:
    image: sebp/elk:latest
    privileged: true
    container_name: dev-elk
    volumes:
      - ./.volumns/data/elk:/var/lib/elasticsearch
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      ES_MIN_MEM: 512m
      ES_MAX_MEM: 512m